// Autogenerated file; do not edit. Rewritten on attach and detach of Fiddler.

// Get the URL to this file from Fiddler by clicking Tools > Fiddler Options > Connections > Copy Browser Proxy Configuration URL.

function FindProxyForURL(url, host){
  return 'DIRECT';
}